In [1]:
print("Alllooo")

Alllooo


In [2]:
import math

In [3]:
math.pi

3.141592653589793

In [4]:
math.cos(90)

-0.4480736161291701

In [5]:
import numpy as np

In [6]:
lista = [1,2,3,4]

In [7]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [8]:
type(np.arange(10))

numpy.ndarray

In [9]:

np.arange(15, dtype=np.int32)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arreglo = [1, 2, 3, 4]  

In [11]:
type(arreglo)

list

In [12]:
np.array(arreglo)

array([1, 2, 3, 4])

In [13]:
lista = [1, 1, [], "S"]

In [14]:
#Vector de unos
np.ones(3)

array([1., 1., 1.])

In [15]:
#Matriz 3x3
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#Matriz identidad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Números aleatorios

In [17]:
#Elementos flotantes del 0 al 1
np.random.random((5,3))

array([[0.19414491, 0.20253045, 0.66021472],
       [0.23156669, 0.71613113, 0.22636736],
       [0.24104622, 0.07783582, 0.1512677 ],
       [0.61161481, 0.10409387, 0.18498496],
       [0.79201176, 0.79002124, 0.99724591]])

In [18]:
#Semillas para los números aleatorios
np.random.seed(123)

In [19]:
#Matrices con números aleatorios
#rando, tamaño de la matriz
np.random.randint(100, size=(10,10))

array([[66, 92, 98, 17, 83, 57, 86, 97, 96, 47],
       [73, 32, 46, 96, 25, 83, 78, 36, 96, 80],
       [68, 49, 55, 67,  2, 84, 39, 66, 84, 47],
       [61, 48,  7, 99, 92, 52, 97, 85, 94, 27],
       [34, 97, 76, 40,  3, 69, 64, 75, 34, 58],
       [10, 22, 77, 18, 15, 27, 30, 52, 70, 26],
       [80,  6, 14, 75, 54, 71,  1, 43, 58, 55],
       [25, 50, 84, 56, 49, 12, 18, 81,  1, 51],
       [44, 48, 56, 91, 49, 86,  3, 67, 11, 21],
       [89, 98,  3, 11,  3, 94,  6,  9, 87, 14]])

Transpuesta

In [20]:
#Matriz con números random del 0 al 100, de tamaño 3x5
matrix = np.random.randint(100, size=(3,5))

In [21]:
matrix

array([[83, 70, 12, 54, 27],
       [38, 17, 61, 74, 99],
       [99, 65, 47, 16,  5]])

In [22]:
#Del 0 al 10, dame 5 elementos. El incremento es uniforme
np.linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [23]:
#Decreciente
np.linspace(50, 10, 5)

array([50., 40., 30., 20., 10.])