In [74]:
import numpy as np

In [75]:
matriz = np.random.randint(101, size=(3,5))

In [76]:
matriz

array([[16, 45, 19, 39,  8],
       [57,  5, 87, 51, 11],
       [77, 65, 98, 89, 61]])

Numpy permite hacer filtros en las matrices, como el siguiente ejemplo

In [77]:
matriz > 30

array([[False,  True, False,  True, False],
       [ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [78]:
#Números mayores a 30 = 0
#matriz[matriz>30] = 0

In [79]:
matriz[matriz>30] 

array([45, 39, 57, 87, 51, 77, 65, 98, 89, 61])

In [80]:
matriz

array([[16, 45, 19, 39,  8],
       [57,  5, 87, 51, 11],
       [77, 65, 98, 89, 61]])

Dos arreglos para llegar a un elemento (coordenadas o fila/columna)
Arr 1: Pilas
Arr 2: Columnas

In [81]:
x = np.where(matriz>30) #Repasar
x

(array([0, 0, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 2, 3, 0, 1, 2, 3, 4], dtype=int64))

In [82]:
matriz[0,0]


16

In [83]:
matriz[x[0][1], x[1][1]]

39